name = "JENVI"
uuid = "cc5456c6-5015-4dea-85b7-cc64c32d0b53"
authors = ["Z.M. Vig <zvig@umd.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
